name: AI PR Comment Bot with Anthropic

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          poetry install

      - name: Print current working directory
        run: pwd

      - name: List all files in the workspace
        run: ls -l $GITHUB_WORKSPACE

      - name: List files in .github/scripts
        run: ls -l $GITHUB_WORKSPACE/.github/

      - name: Set PYTHONPATH to include scripts directory
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE/scripts" >> $GITHUB_ENV

      - name: Run AI PR Review Python Script
        run: |
          echo "Running AI PR Reviewer..."
          python scripts/main.py

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
